-- Databricks notebook source
-- MAGIC %md
-- MAGIC Semantic Layer Definition

-- COMMAND ----------

CREATE OR REPLACE VIEW ${catalog}.${environment}.review_metrics
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "KPIs for Reviews"
  source: ${catalog}.${environment}.fact_reviews
  filter: weighted_score IS NOT NULL
  joins:
    - name: dim_games
      source: ${catalog}.${environment}.dim_games
      on: source.appid = dim_games.appid
  dimensions:
    - name: release_date
      expr: dim_games.release_date
      display_name: 'Release Date'
      comment: 'Release Date of the Game'
    - name: review_date
      expr: source.updated_at
      display_name: 'Review Date'
      comment: 'Date when review was updated'
    - name: name
      expr: dim_games.name
      display_name: 'Game Name'
      comment: 'Name of the Game'
    - name: runs_on_windows
      expr: dim_games.supports_windows
      display_name: 'Runs on Windows'
      comment: 'Whether game runs on Windows'
    - name: runs_on_mac
      expr: dim_games.supports_mac
      display_name: 'Runs on MacOS'
      comment: 'Whether game runs on MacOS'
    - name: runs_on_linux
      expr: dim_games.supports_linux
      display_name: 'Runs on Linux'
      comment: 'Whether game runs on Linux'
    - name: metacritic_score
      expr: dim_games.metacritic_score
      display_name: 'Metacritic Score'
      comment: 'Average rating of game on website Metacritic'

  measures:
    - name: review_count
      expr: COUNT(*)
    - name: avg_weighted_score
      expr: AVG(weighted_score)
      display_name: 'Average Review Score'
      comment: 'Average of the sentiment score generated by AI'
    - name: positive_review_pct
      expr: SUM(CASE WHEN weighted_score > 0 THEN 1 ELSE 0 END) / COUNT(*)
      display_name: 'Postive Review Percentage'
      comment: 'Percentage of reviews with positive sentiment'
    - name: negative_review_pct
      expr: SUM(CASE WHEN weighted_score < 0 THEN 1 ELSE 0 END) / COUNT(*)
      display_name: 'Negative Review Percentage'
      comment: 'Percentage of reviews with negative sentiment'
    - name: median_review_length
      expr: PERCENTILE(LENGTH(review_text), 0.5)
      display_name: 'Median Review Length'
$$

-- COMMAND ----------

-- MAGIC %md
-- MAGIC Descriptions for Fact Table

-- COMMAND ----------

ALTER TABLE ${catalog}.${environment}.fact_reviews
SET TBLPROPERTIES ('comment' = 'Fact table for Game reviews by users');

-- COMMAND ----------

COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.appid IS 'Unique identifier of game';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.recommendationid IS 'Unique identifier of review';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.sponsored_review IS 'If reviewer received game for free or not';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.comment_count IS 'Number of comments on review';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.author_playtime_forever IS 'Number of hours of gameplay by reviewer till now';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.author_playtime_at_review IS 'Number of hours of gameplay by reviewer till review submission';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.review_text IS 'Review content';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.sentiment_score IS 'Sentiment score generated by AI';
COMMENT ON COLUMN ${catalog}.${environment}.fact_reviews.weighted_score IS 'Weighted score to reduce impact of sponsored reviews';

-- COMMAND ----------

-- MAGIC %md
-- MAGIC Game Dimension

-- COMMAND ----------

ALTER TABLE ${catalog}.${environment}.dim_games
SET TBLPROPERTIES ('comment' = 'Dimension table for Games');

-- COMMAND ----------

COMMENT ON COLUMN ${catalog}.${environment}.dim_games.appid IS 'Unique identifier of game';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.name IS 'Name of game';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.release_date IS 'Release date of game';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.supports_windows IS 'Whether or not game runs on Windows';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.supports_mac IS 'Whether or not game runs on MacOS';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.supports_linux IS 'Whether or not game runs on Linux';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.sale_price IS 'Price at which game is sold';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.mat_currency IS 'Currency in which game is sold';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.metacritic_score IS 'Average rating of game on website Metacritic';
COMMENT ON COLUMN ${catalog}.${environment}.dim_games.on_sale IS 'Whether game sold at full price or at a discount';
